# HTTP STATUS CODES
HTTP_STATUS_SUCCESS = 200
HTTP_STATUS_SUCCESS_CREATED = 201
HTTP_STATUS_SUCCESS_NOCONTENT = 204
HTTP_STATUS_ERROR_BAD_REQUEST = 400
HTTP_STATUS_ERROR_NOT_FOUND = 404
HTTP_STATUS_ERROR_CONFLICT = 409
